/*
 * DuyDuc94
 */
package hashfunction.md5;

import static hashfunction.md5.MD5.getHash;
import java.util.*;

/**
 *
 * @author duy20
 */
public class Main {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String s = "DucDuy94";
        System.out.println("Your HashCode Generated by MD5 is: " + getHash(s));
        String s1 = "DucDuy96";
        System.out.println("Your HashCode Generated by MD5 is: " + getHash(s1));
        boolean check = (getHash(s1).compareTo(getHash(s))) == 0;
        System.out.println("Compare s1 to s: " + check);

    }
}
